apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-xykahisg
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-xykahisg:ce2f1a0dc3914ce3dc002e505de970c38616c89f@sha256:309ef4ff0399bfba2e8e5f82bd8f7f3954ae1136ecd6d97264900c05a6c99f68
        name: container-image  
